packages:
  - packages/**

catalog:
  '@types/bcryptjs': ^2.4.2
  '@types/chrome': ^0.0.193
  '@types/crypto-js': 4.1.1
  '@types/firefox-webext-browser': ^94.0.1
  '@types/jsrsasign': ^10.5.4
  '@types/lodash': ^4.17.7
  '@types/netmask': ^2.0.5
  '@types/node': ^22.0.0
  '@types/pako': ^2.0.0
  '@types/sm-crypto': ^0.3.0
  '@types/strict-uri-encode': ^2.0.0
  '@tauri-apps/api': ^2.0.0
  '@tauri-apps/cli': ^2.0.0
  '@tauri-apps/plugin-shell': ^2.0.0
  '@vitejs/plugin-vue': ^5.1.0
  '@vue-macros/reactivity-transform': ^1.0.0
  '@vue/runtime-core': ^3.5.0
  '@vueuse/core': ^11.0.0
  bcryptjs: ^2.4.3
  crypto-js: 4.1.1
  dayjs: ^1.11.12
  ip6: ^0.2.10
  js-base64: ^3.7.4
  js-htmlencode: ^0.3.0
  json5: ^2.2.3
  jsrsasign: ^11.0.0
  jwt-decode: ^4.0.0
  lodash: ^4.17.21
  netmask: ^2.0.2
  normalize.css: ^8.0.1
  pako: ^2.1.0
  pinia: ^2.0.29
  pinia-plugin-persistedstate: ^4.0.0
  sm-crypto: ^0.3.11
  sortablejs: ^1.15.0
  store2: ^2.14.2
  strict-uri-encode: ^2.0.0
  svg-path-bounds: ^1.0.2
  text-decoding: ^1.0.0
  tippy.js: ^6.3.7
  tsup: ^8.2.4
  typescript: ^5.5.0
  utools-api-types: ^3.0.0
  vite: ^5.4.3
  vite-plugin-html-config: ^2.0.2
  vite-plugin-node-polyfills: ^0.22.0
  vite-plugin-pwa: ^0.20.5
  vue: ^3.5.0
  vue-draggable-next: ^2.1.1
  vue-router: ^4.4.0
  vue-tsc: ^2.1.0
  workbox-build: ^7.1.1
  workbox-window: ^7.1.0
  zip-a-folder: ^1.1.5

onlyBuiltDependencies:
  - esbuild
  - vue-demi
