name: 功能建议
description: 提出新功能或改进建议
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你的建议！请描述你希望添加的功能。
  - type: textarea
    id: problem
    attributes:
      label: 使用场景
      description: 描述你在什么场景下需要这个功能
      placeholder: 在做渗透测试时，我经常需要...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 期望方案
      description: 描述你希望的功能表现
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 你目前是怎么解决这个需求的？
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: 补充信息
      description: 截图、参考链接或其他相关信息
    validations:
      required: false
